### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by owenconnorz** [JJMeijer/yasc#1]
![Screenshot_20231119_120825_Samsung Internet.jpg](https://github.com/JJMeijer/yasc/assets/96526481/74d7c442-bce7-45ae-b5ba-00ca5f837f6b)

**Comment by owenconnorz** [comment]
This is after iv login 

![Screenshot_20231119_145431_Opera.jpg](https://github.com/JJMeijer/yasc/assets/96526481/c6d513ac-d5aa-4a96-b203-c5266e4428fe)

@JJMeijer

**Comment by JJMeijer** [comment]
@owencz1998  Could you share which browser you're using? 

Also as a heads-up, currently the UI is only optimized for desktop. Even after login it will look pretty bad on mobile.

**Comment by owenconnorz** [comment]
> @owencz1998  Could you share which browser you're using? 
> 
> Also as a heads-up, currently the UI is only optimized for desktop. Even after login it will look pretty bad on mobile.

Iv tried edge, opera and Samsung Internet mate and no problem will love to see the future updates 😁

@JJMeijer

**Comment by JJMeijer** [comment]
@owencz1998 Login should be working by now, so I'm closing the issue. hopefully in the future a more mobile-friendly UI!

**Comment by owenconnorz** [comment]
Doesn't work on mobile at all iv tried to load in desktop mode but till throws a error after authentication @JJMeijer

**Comment by JJMeijer** [comment]
Apparantly when creating API credentials at developer.spotify.com at first only your own account is allowed to authenticate with the API. which is why it is not working for you. 

If you want to check it out in the future i've added som instructions in the readme to run the app locally.

**Comment by owenconnorz** [comment]
OK thanks mate will have a look into it
